[colors.primary]
background = 'msfxSet(color_bg2)'
foreground = 'msfxSet(color_fg3)'

[colors.normal]
black   = 'msfxSet(color_bg3)'
red     = 'msfxSet(color_red1)'
green   = 'msfxSet(color_green1)'
yellow  = 'msfxSet(color_yellow1)'
blue    = 'msfxSet(color_blue1)'
magenta = 'msfxSet(color_purple1)'
cyan    = 'msfxSet(color_aqua1)'
white   = 'msfxSet(color_fg2)'

[colors.bright]
black   = 'msfxSet(color_bg4)'
red     = 'msfxSet(color_red2)'
green   = 'msfxSet(color_green2)'
yellow  = 'msfxSet(color_yellow2)'
blue    = 'msfxSet(color_blue2)'
magenta = 'msfxSet(color_purple2)'
cyan    = 'msfxSet(color_aqua2)'
white   = 'msfxSet(color_fg4)'

[font]
size = msfxSet(font_size)

[font.normal]
family = "msfxSet(font)"
style = "msfxSet(font_style)"

[shell]
program = "/bin/fish"

[window]
opacity = msfxSet(transparency_invert)

[window.padding]
x = 20
y = 20
