[theme]
theme = "plain"

[theme.overrides]
separator = ""
idle_bg = "msfxSet(color_bg2)"
idle_fg = "msfxSet(color_fg2)"
good_bg = "msfxSet(color_green1)"

[icons]
icons = "material-nf"

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%I:%M') "
