[theme]
theme = "plain"

[theme.overrides]
separator = ""
idle_bg = "#282828"
idle_fg = "#ebdbb2"
good_bg = "#98971a"

[icons]
icons = "material-nf"
icons_format = "{icon}"

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%I:%M') "
