icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "custom"
command ='echo " "'
interval = "once"
[[block.click]]
button = "left"
cmd = "$HOME/.config/i3status/wallpaperSet.sh"
